### ISSUE TITLE
Publish Different Messages to Kafka

### ISSUE THREAD

**Issue by namlt3820** [vlddm/binance-smart-chain-node#4]
I want to use the feature Publish Different Messages to Kafka in binance smart chain node. But from the docs it seems like it's binance chain node feature only. Can someone clarify it? Thank you.

**Comment by vlddm** [comment]
https://satran004.medium.com/kafka-web3-source-connector-publish-web3-compatible-blockchain-data-to-kafka-topics-1310c83decd0
