### ISSUE TITLE
geth version needs to be upgraded

### ISSUE THREAD

**Issue by Mouhssine** [vlddm/binance-smart-chain-node#7]
current geth version isn't supported anymore i guess it get stuck on block 10394607 forever :/

**Comment by vlddm** [comment]
Fixed, pull newer image, do `debug.setHead('0x9e9bef')`

**Comment by Mouhssine** [comment]
should i do debug.setHead('0x9e9bef') on image level or container ? 
im not familiar with docker commands i will be thankful if you can guide me .

**Comment by Mouhssine** [comment]
> Fixed, pull newer image, do `debug.setHead('0x9e9bef')`

i tried it using : 
docker exec binance-smart-chain-node bsc attach --exec debug.setHead="0x9e9bef"

and still stuck there :/

**Comment by vlddm** [comment]
```
docker exec binance-smart-chain-node bsc attach
debug.setHead('0x9e9bef')
```
probably not necessary, my node synced successfully just after image upgrade
check that your bsc node version is 1.1.2

**Comment by Mouhssine** [comment]
![Screenshot from 2021-08-28 15-56-38](https://user-images.githubusercontent.com/3043735/131222137-09c4f572-57b2-4133-b1fe-dcea19e6d51f.png)
when i try bsc attach cmd , it exit without letting me input the command ! but i tried to do it in a single command  like this : 
docker exec binance-smart-chain-node bsc attach --exec debug.setHead="0x9e9bef"


btw the geth version still 1.1.1-beta as shown in the first screenshot even tho i pulled the lastest image .
Thank you
