### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by cventastic** [vlddm/binance-smart-chain-node#8]
Hello I have a question. Why do you use 
https://api.github.com/repos/binance-chain/bsc/releases/tags/v${VERSION}

I would like to use the dockerhub image but it still uses  
ENV VERSION=1.1.1-beta
which has this major evm bug.

Wouldnt it be a good soultion to use 
https://api.github.com/repos/binance-chain/bsc/releases/latest
If not, why?

**Comment by vlddm** [comment]
Dockerhub has `v1.1.2`
Its `ARG VERSION` in Dockerfile so you can pass anything at build time
